### ISSUE TITLE
find keywords in other external installed python libraries

### ISSUE THREAD

**Issue by scottpaxton** [millennialmedia/pyro#13]
The only libraries Pyro currently can find in the local Python installation are Robot Framework's own built-in libraries.  Enhance the library-search utilities (used by both hyperlinking and content assist) to find other user-installed libraries as well.

**Comment by pvshewale** [comment]
Also observed that it can find library from set PYTHONPATH if it is defined as single file module. And unable to find if it is structured as package with __init__,py file.

**Comment by pvshewale** [comment]
Just curios to know if there is any update.

**Comment by scottpaxton** [comment]
Not a huge update other than I've got some changes in progress but uncompleted.  Unfortunately I have obligations that prevent finishing it for at least a few more weeks but I'll update this bug and push out a new release for the update site as soon as some code is ready.

**Comment by scottpaxton** [comment]
Fix live in new update site

External libraries besides Robot built-ins are now found under the python installation.  More-complicated libs, like Selenium2, which import their keyword definitions indirectly from imported modules will still not yet show all content assist or hyperlink options (additional pydev integration work will be needed).
